---
# Source: ajvar/templates/hpa.yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: "demo"
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "demo"
  metrics:
    # - type: External
    #   external:
    #     metric:
    #       name: "monitoring.googleapis.com|uptime_check|request_latency"
    #       selector: 
    #         matchLabels:
    #           resource.type: uptime_url
    #           metric.labels.check_id: "google-uptime"
    #           resource.project_id: '1014212621433'
    #     target:
    #       type: AverageValue
    #       averageValue: 10m
    
  - type: Pods
    pods:
      metric:
        name: "kubernetes.io|pod|network|received_bytes_count"
        selector: 
          matchLabels:
            resource.namespace_name: "demo"
      target:
        type: AverageValue
        averageValue: 1k
